import type { SingleEventId, SingleEventTheme } from "./types";

export const singleEventThemes: Record<SingleEventId, SingleEventTheme> = {
  "ember-year": {
    id: "ember-year",
    title: "Ember Year",
    occasionLabel: "Birthday Evening",
    hostLine: "With love, the Malik family invites you",
    names: "Ayaan Malik",
    dateLabel: "Saturday, 14 November 2026",
    timeLabel: "7:00 in the evening",
    venue: "The Rose Courtyard",
    city: "Lahore",
    message: "Thirty soft years of light — join us for an evening of music, cake, and quiet joy.",
    farewell: "Thank you for celebrating this chapter with us.",
    tapHint: "Tap to open",
    rsvpTitle: "Will you join us?",
    countdownLabel: "Until the celebration",
    targetDate: "2026-11-14T19:00:00+05:00",
    colors: {
      page: "#FFF6F1",
      pageDeep: "#F7E4DA",
      card: "rgba(255, 250, 246, 0.92)",
      ink: "#4A2F2A",
      inkSoft: "#6B4540",
      muted: "#9A736C",
      accent: "#D4897A",
      accentSoft: "#E8B4A8",
      wash: "radial-gradient(ellipse at 30% 20%, #FFE8DF 0%, transparent 55%), radial-gradient(ellipse at 80% 80%, #F5D5C8 0%, transparent 50%)",
      curtain: "linear-gradient(160deg, #F3C4B8 0%, #E8A090 45%, #D4897A 100%)",
    },
  },
  "first-light": {
    id: "first-light",
    title: "First Light",
    occasionLabel: "Engagement Gathering",
    hostLine: "Together with their families",
    names: "Hira & Zain",
    dateLabel: "Friday, 9 October 2026",
    timeLabel: "6:30 in the evening",
    venue: "Garden Pavilion",
    city: "Islamabad",
    message: "A soft beginning — we would be honoured to share this first light with you.",
    farewell: "With gratitude for your presence and your duas.",
    tapHint: "Tap to begin",
    rsvpTitle: "Share your reply",
    countdownLabel: "Until we celebrate",
    targetDate: "2026-10-09T18:30:00+05:00",
    colors: {
      page: "#FFF8FA",
      pageDeep: "#F5E4EA",
      card: "rgba(255, 252, 253, 0.93)",
      ink: "#3F2A33",
      inkSoft: "#5C3F4A",
      muted: "#8F6B78",
      accent: "#C9959E",
      accentSoft: "#E2BDC4",
      wash: "radial-gradient(ellipse at 25% 15%, #FFE8EF 0%, transparent 55%), radial-gradient(ellipse at 75% 85%, #F0D0D8 0%, transparent 50%)",
      curtain: "linear-gradient(165deg, #E8C4CB 0%, #D4A0AB 50%, #C9959E 100%)",
    },
  },
  "lullaby-moon": {
    id: "lullaby-moon",
    title: "Lullaby Moon",
    occasionLabel: "Baby Welcome",
    hostLine: "A gentle announcement from",
    names: "Noor & Faris",
    dateLabel: "Sunday, 22 November 2026",
    timeLabel: "4:00 in the afternoon",
    venue: "Home gathering",
    city: "Karachi",
    message: "Our little moon has arrived. Join us for a quiet afternoon of sweets and blessings.",
    farewell: "Thank you for holding our joy with us.",
    tapHint: "Open the card",
    rsvpTitle: "Will you visit?",
    countdownLabel: "Until we welcome you",
    targetDate: "2026-11-22T16:00:00+05:00",
    colors: {
      page: "#F7FAFF",
      pageDeep: "#E4ECF7",
      card: "rgba(252, 254, 255, 0.94)",
      ink: "#2A3344",
      inkSoft: "#445066",
      muted: "#74829A",
      accent: "#8FA8C9",
      accentSoft: "#C2D2E6",
      wash: "radial-gradient(ellipse at 20% 20%, #E8F0FA 0%, transparent 55%), radial-gradient(ellipse at 85% 75%, #D5E0F0 0%, transparent 50%)",
      curtain: "linear-gradient(170deg, #C8D6E8 0%, #A8BCD8 48%, #8FA8C9 100%)",
    },
  },
  "laureate-dusk": {
    id: "laureate-dusk",
    title: "Laureate Dusk",
    occasionLabel: "Graduation Evening",
    hostLine: "Please celebrate with",
    names: "Sara Qureshi",
    dateLabel: "Thursday, 3 December 2026",
    timeLabel: "5:30 in the evening",
    venue: "Olive Hall",
    city: "Lahore",
    message: "A chapter closes under soft dusk light — dinner, laughter, and a little pride.",
    farewell: "Your company made the journey sweeter.",
    tapHint: "Tap to enter",
    rsvpTitle: "Confirm your seat",
    countdownLabel: "Until the evening",
    targetDate: "2026-12-03T17:30:00+05:00",
    colors: {
      page: "#F6F8F3",
      pageDeep: "#E4EAD8",
      card: "rgba(252, 253, 248, 0.93)",
      ink: "#2C3528",
      inkSoft: "#455040",
      muted: "#74806C",
      accent: "#8A9A72",
      accentSoft: "#C0CBAE",
      wash: "radial-gradient(ellipse at 30% 10%, #EAF0E0 0%, transparent 55%), radial-gradient(ellipse at 70% 90%, #D5DFC4 0%, transparent 50%)",
      curtain: "linear-gradient(155deg, #C5D0B0 0%, #A3B48A 48%, #8A9A72 100%)",
    },
  },
  "silver-thread": {
    id: "silver-thread",
    title: "Silver Thread",
    occasionLabel: "Anniversary Dinner",
    hostLine: "Twenty-five years woven together",
    names: "Amna & Imran",
    dateLabel: "Saturday, 28 November 2026",
    timeLabel: "8:00 in the evening",
    venue: "The Ivory Room",
    city: "Rawalpindi",
    message: "A quiet silver evening — dinner under soft lights, for those who walked with us.",
    farewell: "With love for every year you shared in ours.",
    tapHint: "Open invitation",
    rsvpTitle: "Will you dine with us?",
    countdownLabel: "Until the dinner",
    targetDate: "2026-11-28T20:00:00+05:00",
    colors: {
      page: "#F8F5F0",
      pageDeep: "#E8E0D4",
      card: "rgba(255, 252, 248, 0.94)",
      ink: "#322C26",
      inkSoft: "#4E463D",
      muted: "#8A8074",
      accent: "#B8A48A",
      accentSoft: "#D8CBB6",
      wash: "radial-gradient(ellipse at 25% 18%, #F0E8DC 0%, transparent 55%), radial-gradient(ellipse at 80% 80%, #DDD2C2 0%, transparent 50%)",
      curtain: "linear-gradient(160deg, #D4C6B0 0%, #C4B396 48%, #B8A48A 100%)",
    },
  },
};

export function getSingleEventTheme(id: string): SingleEventTheme | undefined {
  return singleEventThemes[id as SingleEventId];
}

export const singleEventIds = Object.keys(singleEventThemes) as SingleEventId[];
