import type { ContactSettings, Design, NavItem, Occasion, Profile } from "./schema";

export const profile: Profile = {
  meta: {
    status: "draft",
    evidenceRef: "Invitations MVP brief 2026-09-29. Brand and tagline retained; positioning pivoted to digital invitations.",
    lastVerified: "2026-09-29",
    displayPermission: "pending",
  },
  brand: "IntellAte",
  tagline: "IA: Automate the Intellect",
  headline: "Digital invitations designed around your story",
  supporting:
    "Your event, your people, your world — not recycled templates. Choose a design or create something nobody else has.",
  promise: "Don't find the perfect invitation. Create yours.",
};

export const occasions: Occasion[] = [
  {
    meta: {
      status: "draft",
      evidenceRef: "MVP occasion taxonomy from invitations brief 2026-09-29.",
      lastVerified: "2026-09-29",
      displayPermission: "pending",
    },
    slug: "wedding",
    title: "Wedding",
    summary: "Single-day or multi-event celebrations — Mehndi, Baraat, Waleema, and beyond.",
  },
  {
    meta: {
      status: "draft",
      evidenceRef: "MVP occasion taxonomy from invitations brief 2026-09-29.",
      lastVerified: "2026-09-29",
      displayPermission: "pending",
    },
    slug: "birthday",
    title: "Birthday",
    summary: "Milestone birthdays with colour, motion, and a personal guest path.",
  },
  {
    meta: {
      status: "draft",
      evidenceRef: "MVP occasion taxonomy from invitations brief 2026-09-29.",
      lastVerified: "2026-09-29",
      displayPermission: "pending",
    },
    slug: "newborn",
    title: "Newborn / Baby Announcement",
    summary: "Soft announcement experiences for welcoming someone new.",
  },
  {
    meta: {
      status: "draft",
      evidenceRef: "MVP occasion taxonomy from invitations brief 2026-09-29.",
      lastVerified: "2026-09-29",
      displayPermission: "pending",
    },
    slug: "graduation",
    title: "Graduation",
    summary: "Celebrate the achievement with a polished digital invite.",
  },
  {
    meta: {
      status: "draft",
      evidenceRef: "MVP occasion taxonomy from invitations brief 2026-09-29.",
      lastVerified: "2026-09-29",
      displayPermission: "pending",
    },
    slug: "anniversary",
    title: "Anniversary",
    summary: "Intimate or grand — designed around your years together.",
  },
  {
    meta: {
      status: "draft",
      evidenceRef: "MVP occasion taxonomy from invitations brief 2026-09-29.",
      lastVerified: "2026-09-29",
      displayPermission: "pending",
    },
    slug: "engagement",
    title: "Engagement",
    summary: "Announce the beginning with an interactive first impression.",
  },
  {
    meta: {
      status: "draft",
      evidenceRef: "MVP occasion taxonomy from invitations brief 2026-09-29.",
      lastVerified: "2026-09-29",
      displayPermission: "pending",
    },
    slug: "corporate",
    title: "Corporate / Event",
    summary: "Launches, galas, and company moments with premium motion.",
  },
  {
    meta: {
      status: "draft",
      evidenceRef: "MVP occasion taxonomy from invitations brief 2026-09-29.",
      lastVerified: "2026-09-29",
      displayPermission: "pending",
    },
    slug: "something-else",
    title: "Something Else",
    summary: "You name the occasion — we design the invitation around it.",
  },
];

export const designs: Design[] = [
  {
    meta: {
      status: "draft",
      evidenceRef: "Flagship adapted from complete multi-event invitation prototype; personal names anonymized for public MVP.",
      lastVerified: "2026-09-29",
      displayPermission: "pending",
    },
    slug: "aurora-safar",
    title: "Aurora Safar",
    eyebrow: "The Invitation That Started IntellAte",
    summary:
      "A complete multi-event wedding journey — Mehndi, Baraat, and Waleema — as separate colourful worlds inside one invitation.",
    occasions: ["wedding"],
    kind: "multi",
    eventCount: 3,
    eventLabels: ["Mehndi", "Baraat", "Waleema"],
    features: [
      "Cinematic opening sequence",
      "Three themed event worlds",
      "Scratch reveal & countdown",
      "English / Urdu experience",
      "Calendar & maps ready",
    ],
    customizationNotes:
      "Names, dates, venues, host line, colours, music, and event count can all be tailored. Designers refine the concept with you after you request this design.",
    startingPrice: "From PKR 45,000",
    featured: true,
    flagship: true,
    hasLivePreview: true,
    previewSwatch: {
      bg: "#F7F1E8",
      accent: "#C6A15B",
      ink: "#2C261F",
      soft: "#E0C075",
    },
  },
  {
    meta: {
      status: "draft",
      evidenceRef: "Single-event birthday live preview demo — soft peach theme, fictional guests.",
      lastVerified: "2026-09-29",
      displayPermission: "pending",
    },
    slug: "ember-year",
    title: "Ember Year",
    eyebrow: "Single-event birthday",
    summary: "One glowing birthday night — soft peach motion, countdown, and a personal RSVP path.",
    occasions: ["birthday"],
    kind: "single",
    eventCount: 1,
    eventLabels: ["Birthday celebration"],
    features: ["Tap-to-open entrance", "Live countdown", "Guest RSVP path", "Soft peach colour story"],
    customizationNotes: "Swap palette, age milestone, venue, host line, and guest message after you request this design.",
    startingPrice: "From PKR 18,000",
    featured: true,
    flagship: false,
    hasLivePreview: true,
    previewSwatch: {
      bg: "#FFF6F1",
      accent: "#D4897A",
      ink: "#4A2F2A",
      soft: "#E8B4A8",
    },
  },
  {
    meta: {
      status: "draft",
      evidenceRef: "Single-event engagement live preview demo — soft blush theme, fictional couple.",
      lastVerified: "2026-09-29",
      displayPermission: "pending",
    },
    slug: "first-light",
    title: "First Light",
    eyebrow: "Engagement announcement",
    summary: "A soft blush announcement for the moment you say yes — intimate, luminous, share-ready.",
    occasions: ["engagement"],
    kind: "single",
    eventCount: 1,
    eventLabels: ["Engagement"],
    features: ["Announcement-first layout", "Countdown & details", "RSVP for the gathering", "Blush palette"],
    customizationNotes: "Names, proposal story, date, venue, and palette are tailored with you after request.",
    startingPrice: "From PKR 22,000",
    featured: true,
    flagship: false,
    hasLivePreview: true,
    previewSwatch: {
      bg: "#FFF8FA",
      accent: "#C9959E",
      ink: "#3F2A33",
      soft: "#E2BDC4",
    },
  },
  {
    meta: {
      status: "draft",
      evidenceRef: "Single-event newborn live preview demo — powder blue theme, fictional family.",
      lastVerified: "2026-09-29",
      displayPermission: "pending",
    },
    slug: "lullaby-moon",
    title: "Lullaby Moon",
    eyebrow: "Newborn welcome",
    summary: "A powder-blue welcome for someone new — quiet afternoon, sweets, and soft blessings.",
    occasions: ["newborn"],
    kind: "single",
    eventCount: 1,
    eventLabels: ["Baby welcome"],
    features: ["Gentle tap entrance", "Home gathering details", "Blessing RSVP", "Powder blue wash"],
    customizationNotes: "Baby name, parents, date, and colour story are personalised after you request this design.",
    startingPrice: "From PKR 16,000",
    featured: true,
    flagship: false,
    hasLivePreview: true,
    previewSwatch: {
      bg: "#F7FAFF",
      accent: "#8FA8C9",
      ink: "#2A3344",
      soft: "#C2D2E6",
    },
  },
  {
    meta: {
      status: "draft",
      evidenceRef: "Single-event graduation live preview demo — sage dusk theme, fictional graduate.",
      lastVerified: "2026-09-29",
      displayPermission: "pending",
    },
    slug: "laureate-dusk",
    title: "Laureate Dusk",
    eyebrow: "Graduation evening",
    summary: "Sage and soft gold for a chapter closing — dinner, laughter, and a little pride.",
    occasions: ["graduation"],
    kind: "single",
    eventCount: 1,
    eventLabels: ["Graduation"],
    features: ["Dusk entrance", "Venue & timing card", "Seat RSVP", "Sage colour story"],
    customizationNotes: "Graduate name, degree line, venue, and palette are refined with you after request.",
    startingPrice: "From PKR 18,000",
    featured: true,
    flagship: false,
    hasLivePreview: true,
    previewSwatch: {
      bg: "#F6F8F3",
      accent: "#8A9A72",
      ink: "#2C3528",
      soft: "#C0CBAE",
    },
  },
  {
    meta: {
      status: "draft",
      evidenceRef: "Single-event anniversary live preview demo — champagne silver theme, fictional couple.",
      lastVerified: "2026-09-29",
      displayPermission: "pending",
    },
    slug: "silver-thread",
    title: "Silver Thread",
    eyebrow: "Anniversary dinner",
    summary: "Champagne and taupe for years woven together — an intimate silver evening under soft lights.",
    occasions: ["anniversary"],
    kind: "single",
    eventCount: 1,
    eventLabels: ["Anniversary dinner"],
    features: ["Silver-tone entrance", "Dinner details", "RSVP for guests", "Champagne palette"],
    customizationNotes: "Years married, names, venue, and wording are tailored after you request this design.",
    startingPrice: "From PKR 20,000",
    featured: true,
    flagship: false,
    hasLivePreview: true,
    previewSwatch: {
      bg: "#F8F5F0",
      accent: "#B8A48A",
      ink: "#322C26",
      soft: "#D8CBB6",
    },
  },
];

export const contactSettings: ContactSettings = {
  meta: {
    status: "draft",
    evidenceRef: "Business contact channels pending confirmation; do not invent public numbers.",
    lastVerified: null,
    displayPermission: "pending",
  },
  email: null,
  whatsapp: null,
  pendingMessage:
    "Business WhatsApp and email are being confirmed. Until they are published, submit a design request and we will reply through the channel you prefer.",
};

export const navigation: NavItem[] = [
  { label: "Invitations", href: "/invitations" },
  { label: "Occasions", href: "/occasions" },
  { label: "Custom", href: "/custom" },
  { label: "Contact", href: "/contact" },
];
